### ISSUE TITLE
Bug: Character misalignment

### ISSUE THREAD

**Issue by HenYu-Yo** [nvim-lualine/lualine.nvim#1109]
![屏幕截图 2023-10-05 121917](https://github.com/nvim-lualine/lualine.nvim/assets/116161568/6a2075d6-7002-474d-9d42-4b448c8ed0ea)

My lualine had character problems after the installation was completed. I installed fonts-powerline again, but an error occurred.

**Comment by Slotos** [comment]
Lualine doesn't perform font rendering.

The issue is likely to lie with your terminal emulator, your fonts, or both. See if you can do without using patched fonts as a start.

[Kitty](https://sw.kovidgoyal.net/kitty/) is a performant terminal emulator that picks up NerdFontsSymbolsOnly font automagically and can be instructed to pick a font per codepoint if need be.
[WezTerm](https://wezfurlong.org/wezterm/index.html) is another performant terminal emulator that includes nerdfont symbols by default.

Try either with a regular, non-patched font and [NerdFontsSymbolsOnly](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2) present.
