### ISSUE TITLE
Bug: Sometimes buffer inactive color fg and bg are both set to #ffffff

### ISSUE THREAD

**Issue by kdheepak** [nvim-lualine/lualine.nvim#413]
This doesn't happen all the time, but every now and then (without any changes to my neovim configuration), when I open multiple buffers, this happens:

![Screen Shot 2021-10-30 at 3 16 54 PM](https://user-images.githubusercontent.com/1813121/139558566-27b4ee67-ed6a-4f25-b4dd-42b753e476c5.png)

When I print out the value of `lualine_a_inactive`, I get this:

![Screen Shot 2021-10-30 at 3 17 55 PM](https://user-images.githubusercontent.com/1813121/139558593-3bb6a13f-ac25-4683-99f4-62abae6b5ae4.png)

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

I'm not able to consistently reproduce it though. Any time run `PackerClean` and `PackerCompile` after commenting out a plugin and enabling it again, the problem goes away. It does happen again after a while without any changes to my configuration. I even added a `print` in lualine's highlight module, to see if I could figure out where is being set but it didn't seem like that code was ever being hit even when the bug was caused.

I wanted to report it mainly to see if someone had suggestions on how to debug it. It is very likely something in my configuration but I'm unable to figure out what.

**Comment by kdheepak** [comment]
It might have something to do with this section: https://github.com/projekt0n/github-nvim-theme/blob/a70f851cd5fcfff0d2c0fab062d31e4d40a71d52/lua/github-theme/theme.lua#L516-L532

Although, I did experience the same issue with a different theme ( I can't remember which one ) and I ruled out the issue being in the specific theme I'm using.

I currently set `hide_inactive_statusline = false` in my configuration and I'm no longer getting the issue. If it continues to be resolved, I'll close this issue.

**Comment by shadmansaleh** [comment]
This does sound like issue with theme/colorscheme to me because highlighter only gets colors inactive colors from theme and doesn't hardcode any value .

colorschemes do copy structures for similar features which may  cause multiple to have same bug . I haven't seen this occur for me and have heard `hide_inactive_statusline` first time here still trying to figure out why you'd do it in colorscheme . If you don't want to show anything on inactive statusline you should just set sections in inactive status to empty tables not make fg & bg same 🤷‍♂️

**Comment by kdheepak** [comment]
Thanks for the answer. I disabled it and haven’t seen the issue since. I’ll open an issue on the theme repository.
