### ISSUE TITLE
Bug: git diff is displayed incorrectly on tabline

### ISSUE THREAD

**Issue by begss** [nvim-lualine/lualine.nvim#442]
It shows the diff of previously active buffer, not the current one. There's no such issue if diff is on statusline.

Two diffs can even give opposite results:
![image](https://user-images.githubusercontent.com/59313755/142725488-65bc5895-ad42-46bc-b3ee-8d3df432c4fe.png)

**Comment by shadmansaleh** [comment]
By default neo(vim) doesn't updates tabline often . You can try to [update tabline more frequenty](https://github.com/nvim-lualine/lualine.nvim/wiki/FAQ#my-tabline-updates-infrequently) and see if that resolves this issue.

**Comment by begss** [comment]
`:redrawtabline` helps, but tabline is anyway redrawn when current buffer is switched, why lualine tells wrong/outdated info to draw in the first place? Why statusline doesn't suffer from that?

**Comment by shadmansaleh** [comment]
Diffs are fetched asynchronously . When buff change occurs it triggers a diff fetch . But the data isn't updated until diff calculations are done. So on first redraw after buff switch old data is still displayed. And new data gets shown on first redraw after diffs are done.

Because statusline gets redrawn way more often then tabline statusline doesn't suffer from this .

If you need more agile behavior from tabline I'd recommend you to redraw tabline more often like shown in the example I linked above.

I don't consider this a bug. If you agree do close this issue if you don't do convince me otherwise or suggest how this can be resolved.

**Comment by begss** [comment]
OK, thanks for explanation. I don't think I can help in any way.
