### ISSUE TITLE
Bug: Diff colours not following specified preferences

### ISSUE THREAD

**Issue by CrashAndSideburns** [nvim-lualine/lualine.nvim#443]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in existing issues or prs.

### How to reproduce the problem

Add a line to a file in a git repo, then `:w`.

### Expected behaviour
The `+x` string displayed when lines are added to a file in a git repo should be white.

### Actual behaviour
The string displayed is a light green colour.

### Minimal config to reproduce the issue

```lua
require('lualine').setup({
    sections = {
        lualine_a = {
            {
                'diff',
		diff_colors = {
		    added = {
		        fg = '#ffffff'
		    }
		}
            }
        }
    }
})
```

### Additional information
None.

**Comment by shadmansaleh** [comment]
You've got a typo in your config. Option [name](https://github.com/nvim-lualine/lualine.nvim#diff-component-options) `diff_color` not `diff_colors`.

**Comment by evantravers** [comment]
I'm also seeing something similar. My dotfiles are here: https://github.com/evantravers/dotfiles/blob/master/nvim/.config/nvim/init.lua

The colors in the default `'diff'` module just don't match the theme. I kept jumping themes thinking it was an incompatible theme, but it's not quite there.

This is what it looks like with some customization commented out:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/62209/142783578-3c5dcdac-acdc-4096-8374-f8076c0c0406.png">

Trying to use the highlight groups: 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/62209/142783602-8c33262f-4f7f-40f1-af20-34b5773cea27.png">

Hex code appears to work…
<img width="600" alt="image" src="https://user-images.githubusercontent.com/62209/142783624-2b3f8a48-ac4d-4160-b0d2-00a4c13dcbd1.png">

I'll send you a pull request for the readme soon… it looks like it's got some typos in it… https://github.com/nvim-lualine/lualine.nvim/blob/98b9c05b0630cf8cb52cfd546126e8f0ae34d347/README.md?plain=1#L469-L474

**Comment by shadmansaleh** [comment]
@evantravers the docs are correct it seems you've miss understood them. As stated in [color option](https://github.com/nvim-lualine/lualine.nvim#general-component-options) . It can either be a table with `fg`, `bg`, `gui` optional keys or a string of highlight group name . Here fg & bg needs to be color definition (rgb string/color name string/cterm color number) . So `{fg = 'hl_group_name'}` is invalid config. That's why you config isn't working.

hl group name isn't supported for fg/bg for two reasons
- When you say `fg = 'DiffAdded'` I don't know if you want the foreground color of DiffAdded to be used for fg or the background color.
- hl group name overlaps with currently supported color_name(red, green, grey) strings . It's not possible to completely distinguish them from one another.

If you want to use hl[_groups for fg/bg highlighting you can utilize a helper function like https://github.com/nvim-lualine/lualine.nvim/blob/98b9c05b0630cf8cb52cfd546126e8f0ae34d347/lua/lualine/utils/utils.lua#L11-L28

For example
```lua
local get_color = require'lualine.utils.utils'.extract_highlight_colors
.....
diff_color = {
   added = {fg = get_color('DiffAdded', 'fg')},
}
```

**Comment by shadmansaleh** [comment]
@evantravers I've added more fallbacks for diff components colors . The issue you were facing with diff colors not matching the theme should be unlikely to occur . Checkout if https://github.com/nvim-lualine/lualine.nvim/commit/8725c63941b04c91289a3502acba87c42ac2f082 fixed the issue for you.

**Comment by evantravers** [comment]
Thanks @shadmansaleh, that looks great!

![image](https://user-images.githubusercontent.com/62209/142801559-162f255e-de0e-438d-89c1-7520515f833e.png)
