### ISSUE TITLE
Show separators around all tabs in tabline

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-lualine/lualine.nvim#513]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

`init.vim`:
```
call plug#begin(stdpath('data') . '/plugged')

Plug 'nvim-lualine/lualine.nvim'

" Initialize plugin system
call plug#end()

lua << EOF
require('lualine').setup {
    options = {
        always_divide_middle = false,
        },
    tabline = {
        lualine_b = { {'tabs', separator ={left='', right=''}, max_length=99, mode=2}}

        }
    }
EOF
```

and create some tabs

### Expected behaviour

I would expect the separator to show even around the current tab

### Actual behaviour

The current tab is missing separators (here, the 4th tab is focused)

![image](https://user-images.githubusercontent.com/16707112/147494179-5043b2b0-fd9b-425d-af86-43b598481833.png)

**Comment by shadmansaleh** [comment]
1. Separator is a component option . Since tabs itself in one component that option applies to entire tabs not individual tab (if that makes sence) .
2. There are 2 kind of tab dividers one between inactive tabs and other between active & inactive tabs. 1st type inherits is like component_separators (hence inherits from that option) & 2nd one is like section_seperator (inherits value from that option) .

Both type of separators are being drawn bit for you 2nd type is invisible because your both active & inactive tab has same color .

You should use the active_color option to set a different color for active tab.

**Comment by SimonMandlik** [comment]
Thank you, I think I understand.

Setting `active_color` unfortunately makes no difference 

```
call plug#begin(stdpath('data') . '/plugged')

Plug 'nvim-lualine/lualine.nvim'

" Initialize plugin system
call plug#end()

lua << EOF
require('lualine').setup {
    options = {
        always_divide_middle = false,
        },
    tabline = {
   	lualine_b = { {'tabs', tabs_color = { active = '#112233', inactive = '#000000' }, max_length=99, mode=2}} }
    }
EOF
```

results into 

![image](https://user-images.githubusercontent.com/16707112/147499863-418858ca-0697-44c1-b3d0-05ddefb15144.png)

**Comment by shadmansaleh** [comment]
You are suppose to set active to a table containing fg & bg ( mainly you need bg )

For example:
```lua
lualine_b = { 
  {'tabs',
      tabs_color = {
        active    = {fg = '#000000', bg = '#112233'},
        inactive = {fg = '#112233', bg = '#000000'}, 
     },
     max_length=99,
     mode=2
   }
}
```
See [color](https://github.com/nvim-lualine/lualine.nvim#general-component-options) for how colors are configured in lualine.

**Comment by SimonMandlik** [comment]
Great, thanks for the help :)
