### ISSUE TITLE
Bug: error executing lua Keyboard interrupt in function 'matchlist' [E5108]

### ISSUE THREAD

**Issue by kylo252** [nvim-lualine/lualine.nvim#531]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
This is hard to reproduce sadly, or at least I'm not sure how. But it seems to get triggered when saving a file, and there are a few autocmds executing on `BufWritePost`, like `buf.lsp.formatting_sync()`

### Actual behaviour

```logtalk
E5108: Error executing lua Keyboard interrupt
stack traceback:
        [C]: in function 'matchlist'
        ...pack/packer/start/lualine.nvim/lua/lualine/component.lua:78: in function 'apply_padding'
        ...pack/packer/start/lualine.nvim/lua/lualine/component.lua:182: in function 'draw'
        .../packer/start/lualine.nvim/lua/lualine/utils/section.lua:26: in function 'draw_section'
        ...rvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:153: in function 'statusline'
        ...rvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:319: in function <...rvim/site/pack/packer/start/lualine.nvim/lua/lualine.lua:300>
```

```console
:version
NVIM v0.7.0-dev+792-gc46f7caad
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by hatsu

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional information

Is it possible to defer the execution of the `draw` function?

**Comment by shadmansaleh** [comment]
Can you describe what you were doing when this error occurred ? Were you pressing `CTRL-C` ?

`draw` is essential for updating statusline . Defer it to when ? Also deferring might cause various kinds of inconsistency bugs.

Also deferring  draw won't solve it. As when neovim receives a keyboard interrupt it halts lua evaluation . So if lualine or any other plugins gets caught in this it'll fail . And noting can really be done on plugins side to prevent that as far as I understand . As plugin can't prevent neovim from killing it :P .

We had a previous issue like this #122 there user was using `<C-c>` as replacement of `<Esc>` . Back then it was [decided](https://github.com/nvim-lualine/lualine.nvim/issues/122#issuecomment-788415418) that it's not something lualine can fix . Instead a [workaround](https://github.com/nvim-lualine/lualine.nvim/issues/122#issuecomment-794475367) was recomended to map <C-c> to <Esc>.

**Comment by kylo252** [comment]
> Can you describe what you were doing when this error occurred ? Were you pressing `CTRL-C` ?

It's actually `<C-s>` that I have bound to `:w`

> Defer it to when? 

I was thinking either `vim.schedule` or `vim.schedule_wrap`.

> Also deferring might cause various kinds of inconsistency bugs.

Yeah, I'm wondering how that can work for something like lsp-progress.

> So if lualine or any other plugins gets caught in this it'll fail . 

I also use `<C-c>` but the error is so rare that I wouldn't be able to tell you the exact combination. Could it be something to do with https://github.com/neovim/neovim/issues/14303 ?

> We had a previous issue like this #122 there user was using `<C-c>` as replacement of `<Esc>` . Back then it was [decided](https://github.com/nvim-lualine/lualine.nvim/issues/122#issuecomment-788415418) that it's not something lualine can fix.

My plan here is just to try to look for any potential fixes in regard to timing, basically.

**Comment by shadmansaleh** [comment]
> I was thinking either vim.schedule or vim.schedule_wrap.

`shedule_wrap` on draw will be a very bad idea . As it'll easily make statusline out of sync.

> I also use <C-c> but the error is so rare that I wouldn't be able to tell you the exact combination.

It's very rare to happen and nothing really can be done on lualine's part to resolve it that's why it's considered not a lualine issue.

> Could it be something to do with neovim/neovim#14303 ?

TBH I don't know .

> My plan here is just to try to look for any potential fixes in regard to timing, basically.

Currently lualine's update attached to neovim's statusline redraw . Whenever neovim wants to update the statusline it asks lualine what the statusline should look like and lualine provides that info . I'm not sure what can be done about timing here.

Also in vim/neovim once statusline expression hits an error vim/neovim resets the statusline expression . This is done so user doesn't get constantly spammed about error in statusline . But as a side effect of this once an error occurs lualine looses control over statusline .

I guess I could try implementing a retry mechanics so lualines retries updating the statusline on first few failures before completely giving up . That probably will make this error disappear . But wouldn't really know for sure as this error is so hard to reproduce.

**Comment by shadmansaleh** [comment]
@kylo252 try using #534 for a while and see if the issue occurs in that branch.
