### ISSUE TITLE
Bug: filetype icon doesn't update when filetype is changed

### ISSUE THREAD

**Issue by adaitche** [nvim-lualine/lualine.nvim#537]
When changing the filetype of a buffer, e.g. via `:setfiletype text` the filetype icon doesn't change. Below is an example. I opened a Python file and changed the filetype to "text". The filetype name changed accordingly. However the filetype icon stayed at Python.

![image](https://user-images.githubusercontent.com/25004501/148513349-b38eacb6-a5d5-448e-85bd-01d904aa6e79.png)

### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

**Comment by shadmansaleh** [comment]
It's because nvim-web-devicons basically has it's own filetype detection. It [provides](https://github.com/kyazdani42/nvim-web-devicons#get-icon) icons based on filename/file_path. Doesn't really let us provide the filetype . This issue can be fixed if nvim-web-devicons adds a way to get icon based of filetype 🤷‍♂️.

**Comment by adaitche** [comment]
I see, it is not really a bug in lualine, I will close the issue. Thanks for the explanation. 

Regarding the usecase. I often use scratch buffer for various things. Sometimes I would write out some code (e.g. while reviewing a PR) and switch the filetype to `python` to have syntax highlighting. Afterwards I might use the same scratch buffer to outline some text and would switch the filetype to text (to disable syntax the syntax highlighting).
