### ISSUE TITLE
Bug: Activating (placing components in) the tabline breaks Neovim's splash screen.

### ISSUE THREAD

**Issue by AesaraB** [nvim-lualine/lualine.nvim#542]
### Self Checks
- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem
1. Configure the lualine tabline with components
2. Save changes
3. Restart Neovim

### Expected behaviour
When launching neovim, the user is greeted with the Neovim splash screen
![image](https://user-images.githubusercontent.com/64518882/148722507-51453ec7-d1e9-44ad-8655-9433ba158049.png)

### Actual behaviour
The splash screen is missing when the tabline is present; this issue does not occur on other buffer/tabline plugins.
![image](https://user-images.githubusercontent.com/64518882/148722415-0a63e26d-68a2-4583-94da-c6b2c77403f3.png)

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

```lua
require('packer')startup(function(use)
	use{'nvim-lualine/lualine.nvim', requires = 'kyazdani42/nvim-web-devicons'}
end)

require('lualine').setup {
	tabline = {
		tabline_c = {'buffers'}
	}
}
```

**Comment by shadmansaleh** [comment]
It looks like redrawtabline during tabline [initialization](https://github.com/nvim-lualine/lualine.nvim/blob/bc5c2f5658821f98e55013eb3bec9d540c420470/lua/lualine.lua#L262) is causing neovims splash screen to disapear . I'm not really sure why . The redraw tabline is necessary as neovim doesn't seem to redraw the tabline when tabline option is set . Without the redraw tabline reamains empty until some other tabline redraw event is triggered .

The origin of this issue might be because of an upstream bug .

**Comment by AesaraB** [comment]
Hm, [tabline.nvim](https://github.com/kdheepak/tabline.nvim/blob/main/lua/tabline.lua) doesn't have this error. It calls ``vim.cmd([[redrawtabline]])`` rather than ``vim.api.nvim_command('redrawtabline')``, I haven't worked with nvim plug-ins (though I'd like to start learning eventually, a lot on my spring cleaning list before I get to that); would you be alright with testing out that swap?

If ``vim.api.nvim_command('redrawtabline')`` is the problem I'll create an issue on neovim's tracker.

**Comment by yads** [comment]
I don't actually think it has anything to do with the redraw. Playing around with it: removing the redrawtabline call doesn't affect this behaviour. I think the issue is more fundamental to how the plugin is set up.

**Comment by yads** [comment]
@shadmansaleh actually after doing some more info, I think the problem is that the tabline is set up in a different way than the status line. If I move the code from set_tabline into the main setup function and remove the code in set_tabline, I see the splash screen as intended:
![image](https://user-images.githubusercontent.com/527463/152218142-01bada86-085f-4ee9-b9f3-14a4a0420e5b.png)

Is there a way to make the tabline setup more inline with how the status line is set (i.e. in the setup function, rather than set_tabline)?

**Comment by shadmansaleh** [comment]
Sorry for the late reply . I didn't see you comments . I've tried moving set tablines codes around as you suggested but seems splash screen always disappears if `redrawtabline` is ran . Without redraw tabline the tabline sometimes just doesn't get drawn at startup (In that case tabline appears as a blank bar until next redraw happens) .
