### ISSUE TITLE
Feat: different background color for modified windows

### ISSUE THREAD

**Issue by renkam** [nvim-lualine/lualine.nvim#553]
### Requested feature

I would like to set separate custom color to all the modified windows' statuses.
So in short. When I open an existing file, the colors are 'normal'. If I modify the file it should have different background color. Then if I open another file in a split I would like to see the modified file background status color to be more intense to indicate, that I am leaving  window with unsaved changes.

### Motivation

I think it is important to not forget that something is modified and not written yet if you working with multiple splits, or do a variable rename and other open buffers are changed. The modified status indicator `[+]` is not enough to notify user about that, especially when often inactive windows have darkened foreground color.

**Comment by shadmansaleh** [comment]
duplicate #335 #315

This has been proposed before and decided this won't be included out of the box with lualine .

**Comment by renkam** [comment]
Looks like the component (from #335)  is working.
Maybe it is worth mentioning about it in readme file?
I was looking issues for this topic and couldn't find anything useful, and probably there are more people like me (third duplicate).

Also I can'd understand why you don't want to include this to lualine. It is such useful feature that for some reason no one want to implement. Take a look on other editors/ide they all have some sort of indicator for unsaved files.

**Comment by shadmansaleh** [comment]
> Maybe it is worth mentioning about it in readme file?

I've added it to [component-snippets](https://github.com/nvim-lualine/lualine.nvim/wiki/Component-snippets#changing-filename-color-based-on--modified-status)

>  I can'd understand why you don't want to include this to lualine

I think changing colors based on modified status fot sections a bad idea (airline basically allows themes to specify two themes one for filename not modified and one for modified) . Maybe I'd reconsider adding this just to filename component as opt in feature. Personally I like  providing users a way to customize instead of providing everything out of the box (It's impossible to please everyone :D) . Extened components in config was added in response to first issue about color changing filename .

> Take a look on other editors/ide they all have some sort of indicator for unsaved files.

Even then I think this belongs to tabline (bufferline) rather then in windows statusline . For example [nvim-bufferline](https://github.com/akinsho/bufferline.nvim) shows a nice colored dot based on modified
 status .
