### ISSUE TITLE
Feat: Allow term and gui colors for single theme

### ISSUE THREAD

**Issue by katawful** [nvim-lualine/lualine.nvim#561]
### Requested feature
A format to allow a single theme to use both `cterm` and `gui` colors for a single `fg`/`bg` value for a section

### Motivation
Colorschemes should be as seamless as possible. NeoVim already has a built in feature to tell if GUI colors are in use or not, a separate theme dedicated to just cterm users isn't very intuitive

**Comment by shadmansaleh** [comment]
Do you want different colors in your cterm theme & gui theme ? In that case you can just use a different theme name and conditionally load either in your lualine setup 

```lua
require'lualine'.setup {
  options = {
    theme = vim.o.terguicolors and 'onedrak' or 'onedrak_cterm'
  }
}
```

Otherwise it's more seamless that when gui/cterm color is given lualine handles the other . This also lowers the bar of theme creation .
