### ISSUE TITLE
Allow components to not change color when vim mode changes

### ISSUE THREAD

**Issue by n0bra1n3r** [nvim-lualine/lualine.nvim#571]
### Requested feature

When vim switches modes, the statusline component colors and tabline component colors change. I would like to disable this effect per component. Perhaps a `mode_color` component option?

### Motivation

I am using the tabline feature to render certain components in the tabline. Since the tabline is not updated as frequently as the statusline, sometimes the colors desynchronize.

![image](https://user-images.githubusercontent.com/48817555/152647568-ac7c1772-673a-41a3-8771-0f0f7a074838.png)

This will allow further customizability and control, especially for those who use the tabline feature.

**Comment by shadmansaleh** [comment]
TBH I don't like current behavior of modes changing color of all components at all . This behavior predates me and currently we are pretty much locked as that's how themes are set .

 I'd really like to change theme format to something like following:
```lua
local theme = {
  sections = {a={}, b={}, c={}, (optional x, y, z)},
  inactive = {a={}, b={}, c={},  (optional x, y, z)}, -- optional inactive status color customization
  tabline = {a={}, b={}, c={},  (optional x, y, z)}, -- optional tabline color customization
  components = { -- optional component specific color customization
    mode = { (mode colors effecting only mode compoent) },
   ....
   (other components)
}
```
But that will basically break all themes in existence .Since there are a ton of themes out of this repo in colorschemes I can't fix this without serious breakage for users :/


> I would like to disable this effect per component. Perhaps a mode_color component option?

You can use `color` option (with both fg & bg) and set a default color for that component and it won't change color with mode. As current mode based color change is done on section level making it stop on component level with an option like `mode_color=false` would require a ton of code change .It'll be too much effort for little gain in my opinion. So I think I'll just leave is a solved by `color` option unless in some time I actually decide to rewrite the themes .

**Comment by n0bra1n3r** [comment]
Thanks! Yes explicitly setting the color in the components works well enough for me.
