### ISSUE TITLE
Bug: Slow startup time?

### ISSUE THREAD

**Issue by ajukraine** [nvim-lualine/lualine.nvim#654]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### Environment
- Neovim: nightly (NVIM v0.8.0-dev+3-g3f2e9298b)
- OS: MacOS Monterey 12.3.1
- Device: MacBook Pro (16-inch, 2019)

### How to reproduce the problem

1. Install [vim-plug](https://github.com/junegunn/vim-plug)
2. Install [vim-startuptime](https://github.com/dstein64/vim-startuptime)
3. Install status line plugins via 'vim-plug'
    - [lightline](https://github.com/itchyny/lightline.vim)
    - [lualine](https://github.com/nvim-lualine/lualine.nvim)
    - [airline](https://github.com/vim-airline/vim-airline)
    - [express_line](https://github.com/tjdevries/express_line.nvim)
 4. Create config file with minimal/default setup for each plugin and comment them out
 5. For each status line plugin repeat procedure
     1. Open 'nvim'
     2. Execute command `:StartupTime`
     3. Execute command `:StartupTime --tries 20`
     4. Execute command `:StartupTime --tries 100`
     5. Note down each result

### Expected behaviour

Lualine has fastest average startup time for 1, 20 and 100 tries.

### Actual behaviour

Lightline and express_line are faster.

| tries | control | lightline | lualine | airline | express_line |
| -     | -       | -         | -       | -       | -            |
| 1     | 29.8 ms | 37.1 ms   | 42.8 ms | 80.7 ms | 34.6 ms      |
| 20    | 25.7 ms | 32.4 ms   | 35.1 ms | 76.2 ms | 30.0 ms      |
| 100   | 25.4 ms | 32.2 ms   | 35.2 ms | 77.5 ms | 29.9 ms      |

### Minimal config to reproduce the issue

https://gist.github.com/ajukraine/a47651378ff15aeacd4cdb0ff997c4fd
```lua
local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug 'dstein64/vim-startuptime'

-- Option 1: control
Plug 'itchyny/lightline.vim'

-- Option 2: lualine
-- Plug 'nvim-lualine/lualine.nvim'

-- Option 3: airline
-- Plug 'vim-airline/vim-airline'

-- Option 4: express_line
-- Plug 'nvim-lua/plenary.nvim'
-- Plug 'tjdevries/express_line.nvim'

vim.call('plug#end')

-- Option 2: lualine
-- require('lualine').setup()

-- Option 4: express_line
-- local generator = function()
--     local el_segments = {}
--
--     table.insert(el_segments, require('el.builtin').file)
--     table.insert(el_segments, require('el.extensions').mode)
--     table.insert(el_segments, require('el.extensions').git_changes)
--
--     return el_segments
-- end
-- require('el').setup { generator = generator }

```

**Comment by shadmansaleh** [comment]
I ran it on linux for 100 runs here's the result I got.
```
control: 17.2ms
lualine: 24.8ms
lightline: 25.5ms
airline: 79.9ms
```
It's still marginally faster then lightline . It's possible on mac lua is slightly slower or viml slightly faster resulting in this  difference shifting on the other side . To be honest I'm happy with the startuptime even if it's slightly slower than lightline . lualine provides way more features and customizability compared to lightline that make up for it. If it's loading up under 10ms that's already really fast not really worth spending hours trying to improve it by another ms.

**Comment by ajukraine** [comment]
In general I agree that few milliseconds might not worth the efforts. I was just trying to validate the performance argument in the top of Readme (as it was quite outdated, 20-09-2021).

Also as person who rarely used status line plugins before I was curious about the options. As I am monitoring startup time quite closely, I have noticed that lualine was constantly adding 10ms+. The overall startup time is around 100ms (with 20+ plugins installed). My workflow is very often based on opening nvim from terminal for a singe file, work there, close the nvim and repeat with another file. So basically I get that startup time penalty quite often.

So I am very into finding fastest one, that also supports git, diagnostic and mode components. I really like lualine for it's functionality, but if there is another plugin with faster/better performance and also satisfying my needs, then I would be very glad to find that out.

**Comment by shadmansaleh** [comment]
There are actually lots of statusline plugins most even I haven't tested most of them myself. [awesome-neovim](https://github.com/rockerBOO/awesome-neovim#statusline) repo has a list of lua statusline plugins you could try them and see which one is fastest.

If you truly want fastest one possible you'll need to write a custom one tailored toward your personal usecase . As a general purpose one will always have some level of overhead. If your have something like gitsigns installed it's really easy to get git branch & diff in you statusline, diagnostics is built into neovim and mode is pretty much just quarying neovim for current mode and mapping it to a more readable name.

Also If you aren't using already try [impatient.nvim](https://github.com/lewis6991/impatient.nvim) . It's pretty much a must have for faster startuptimes.

Personally I feel startuptime gets over exaggerate in neovim/vim community . I just don't feel like you're loosing productivity because of your editor starting 10ms slower. For comparison blinking an eye takes 100-400ms. Now think about it you're loosing as much productivity as opening neovim 10-40 times with lualine in a blink it's that much .

**Comment by ajukraine** [comment]
Thank you for tips. You're probably right that it's exaggerated :) Nerd are nerds. Before vim/neovim I was used to bloat IDEs like Visual Studio, so... Yeah.
