### ISSUE TITLE
Bug: lualine doesnt seem to disable correctly after recent updates 

### ISSUE THREAD

**Issue by Rishabh672003** [nvim-lualine/lualine.nvim#747]
### Self Checks

- [X] I'm using the latest lualine.
- [X] I didn't find the issue in exsisting issues or prs.

### How to reproduce the problem

Set lualine to get disable while certain buffertypes like alpha-dashboard or nvim-tree

### Expected behaviour
lualine disables itself and nothing is visible there
like this -> 
![image](https://user-images.githubusercontent.com/53911515/180478554-1cb67f92-5afb-42dc-8f96-c735a13c0bd1.png)

### Actual behaviour
but what happens is this ->
![image](https://user-images.githubusercontent.com/53911515/180478634-5a130627-d349-47cc-a0f5-9f20fc06ffa4.png)

### Minimal config to reproduce the issue

<details>
<summary>Config</summary>

</details>

**Comment by shadmansaleh** [comment]
Lualine is still disabling is self. What's getting rendered is the your default built in statusline. Before recent changes to redraw mechanics we were setting an expression global option statusline and dispatching statuslines for different windows from result of that expression. Now we set the window local option statusline instead. 

Before even on disabled filetypes lualine was still there only it was drawing empty now lualine is not at all there so neovim is drawing the default statusline.

To get empty line on disabled filetypes like before you can set the global statusline option to a space that way that global statusline option will be rendered instead of the builtin default statusline.

```lua
vim.go.statusline = ' '
```

**Comment by Rishabh672003** [comment]
i set the global-line like you said and it does now show nothing now, but now i have another problem now like when i open neovim now it does a flash before showing alpha also the same thing happens when i open nvim-tree
Here's the screen recording of it happening - https://imgur.com/a/FGYRowK

**Comment by shadmansaleh** [comment]
That's odd . I'll have to look into it . Can you provide an isolated minimal_reproduction config with [nvim_isolated_conf.sh](https://github.com/nvim-lualine/lualine.nvim/blob/master/scripts/nvim_isolated_conf.sh)

**Comment by shadmansaleh** [comment]
Can you confirm, it's fixed in 6fbc35b ?

**Comment by Rishabh672003** [comment]
i tried running your script but it is just giving me an error 
![image](https://user-images.githubusercontent.com/53911515/180589190-271008f7-e131-45c0-ac3c-8c818744550f.png)

**Comment by Rishabh672003** [comment]
yup @shadmansaleh its fixed in the latest version, thank you so much
also look into that minimal config script thats not

**Comment by shadmansaleh** [comment]
I think you downloaded the github webpage on the script and tried to ran it instead of getting the raw script😆. The script is already available with lualines installation under scripts forlder so you don't need to download it . If you're downloading remember to download the raw script https://raw.githubusercontent.com/nvim-lualine/lualine.nvim/master/scripts/nvim_isolated_conf.sh

**Comment by Rishabh672003** [comment]
you are right, my bad

**Comment by Rishabh672003** [comment]
@shadmansaleh the recent commit did fixed my previous issues but now lualine has become very slow in disabling itself like it takes a second or two sometimes to disable itself
Here's the screen-recording for you - https://imgur.com/a/HNasGtx

**Comment by shadmansaleh** [comment]
I can't reproduce it . but fb9a0ebbd4dc38e183886a828170c8aebd49544d should help . See if it still happens for you now .

Also with 292c6bbcce6cae74c6f742356cc436d125081521 you no longer need to set the statusline option yourself to hide builtin statusline

**Comment by Rishabh672003** [comment]
thanks man that setting of statusline was the thing causing the issue now its fine
