### ISSUE TITLE
The refresh timeout is causing unwanted behavior for my setup

### ISSUE THREAD

**Issue by augustocdias** [nvim-lualine/lualine.nvim#758]
Is there a way to disable the refresh timeout and go back to the old behavior?

Basically in my setup when I have the cursor over bracket, parenthesis or whatever makes a block, which the matching is outside the viewport, it will replace the status bar with the line of the matching block.

You can see an example in the picture bellow on how it looks. The refresh is basically erasing it and going back to the status line. This is provided by matchup. If there's a way to accomplish a similar behavior with lualine, it would be even better as I could just use a session in it instead of replacing the whole thing as matchup does.

![Screenshot 2022-07-26 at 11 22 51](https://user-images.githubusercontent.com/1080789/180972725-6012df88-d8d1-4881-9123-91bce26dcc0c.png)

**Comment by shadmansaleh** [comment]
> Is there a way to disable the refresh timeout and go back to the old behavior?

You can pin your lualine version to a older commit but you won't be getting updates. We can't relay on older refresh method because there is no way to disable winbar in certain windows. I'd prefer if neovim added an option that disables winbar/if winbar got disabled when winbar expe evals to empty string . But currently I don't see it happening.

> If there's a way to accomplish a similar behavior with lualine

From their [readme](https://github.com/andymass/vim-matchup#customizing-the-highlighting-colors) it seems they expose the stl string through `MatchupStatusOffscreen()` if `g:matchup_matchparen_offscreen.method` is set to `status_manual`.

In that case try setting method to `status_manual` and add `'MatchupStatusOffscreen'` to your lualine config in a section.
