### ISSUE TITLE
Bug: Lualine does not respect `statusline=0`

### ISSUE THREAD

**Issue by Pocco81** [nvim-lualine/lualine.nvim#776]
### Self Checks

- [x] I'm using the latest lualine.
- [x] I didn't find the issue in exsisting issues or prs.

### Expected behaviour

Lualine should be hidden when setting `statusline=0`

### Actual behaviour

It "flashes" as in "disappear and then appear back instantly"

### Aditional information

I wanna make a command to toggle on and off lualine. Setting `statusline=0` works fine for every other statusline but not for this one. Would it be possible for you (the author) to introduce an api to forcefully show/hide lualine?

Thanks :)

Edit: also, setting `laststatus=0` does hide Lualine, but if you have two windows stacked up then it only hides it for the bottom win. The same does not happen for vertical splits. Try: `rightbelow split` and set `statusline=""` and `laststatus=0`. Lualine will still be visible...

**Comment by shadmansaleh** [comment]
> Lualine should be hidden when setting statusline=0

I see, lualine now uses window local statusline option so changing the global one won't have an effect. 

Also you should probably use  statusline="%#NORMAL#" instead of 0.

> Would it be possible for you (the author) to introduce an api to forcefully show/hide lualine?

Sure we can add a proper way to do it.

Although there would still be plugins that sets it's own statusline for it's own window . Those would still break  truezen . Did you try asking neovim devs to add an option to hide statusline ?

**Comment by shadmansaleh** [comment]
Use `require'lualine'.hide()` see [here](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine)

**Comment by Congee** [comment]
ummm, adding a `hide()` api does not change the behavior of https://github.com/nvim-lualine/lualine.nvim/blob/fffbcb829288c3ca366f17cdb8d46aefb5c1d6f3/lua/lualine.lua#L508

FWIW, I'm using https://github.com/vimpostor/vim-tpipeline to merge the vim statusline into the tmux statusline. No statusline should show in vim in this case. Is there any workaround if you won't possibly make a change?

**Comment by Congee** [comment]
Nevermind, I will just use autocmd to set laststatus=0 on these events https://github.com/nvim-lualine/lualine.nvim/blob/fffbcb829288c3ca366f17cdb8d46aefb5c1d6f3/lua/lualine.lua#L30

**Comment by shadmansaleh** [comment]
`hide` should reset the value of laststatus to the value before lualine took over that option

https://github.com/nvim-lualine/lualine.nvim/blob/fffbcb829288c3ca366f17cdb8d46aefb5c1d6f3/lua/lualine.lua#L530

so if you set laststatus=0 before calling lualine setup then use hide it should set it to 0.

if you don't want statusline in you nvim why do you need a statusline plugin I'm a bit confused here

**Comment by Congee** [comment]
Well, I use a plugin that puts vim `statusline` into tmux the status bar. It still shall be rendered and displayed in tmux but not vim. That's why laststatus shall be set to 0.

Unfortunately, `hide()` affects both laststatus and statusline. And my workaround above using those events still are not perfect 😅
