### ISSUE TITLE
Feat: github copilot status indicator

### ISSUE THREAD

**Issue by brunobmello25** [nvim-lualine/lualine.nvim#778]
### Requested feature

status indicator for github copilot similar to the one vscode has

### Motivation

sometimes github copilot takes a good few seconds to process it's suggestion, it would be nice to have an indicator that shows it's processing something.

Here it's how it looks in vscode:

when it's idle:

![image](https://user-images.githubusercontent.com/29875060/182674955-f247631c-8020-4941-963f-2cdd2e8e7ded.png)

when it's processing:
![image](https://user-images.githubusercontent.com/29875060/182675129-142574eb-6ca8-41eb-8c1e-10cfc599a789.png)

**Comment by shadmansaleh** [comment]
I doubt [copilot.vim](https://github.com/github/copilot.vim) exposes that status info at least I don't see anything like that mentioned anywhere in their docs. Either way it's external integration that I don't even use so I'm not interested implementing or maintaining it (It'll probably break without me knowing anyway).

If you can figure out how to get that status info you can easily display it in lualine with custom component like  simple lua/vim function/variables .

In case of vscode ithe copilot plugin for vscode is the one that implements the status indicator your seeing . Your best bet is to get copilot.vim to expose that info in some manner . Since they have issues and discussions disabled not sure what you can do about it though .
