### ISSUE TITLE
Bug: Can't display background color

### ISSUE THREAD

**Issue by johnbitcn** [nvim-lualine/lualine.nvim#804]
<img width="346" alt="截屏2022-08-18 15 29 55" src="https://user-images.githubusercontent.com/1518771/185337472-f591f4f1-cbde-4096-9168-7db4837eadfc.png">
<img width="346" alt="截屏2022-08-18 15 30 02" src="https://user-images.githubusercontent.com/1518771/185337502-41b43cbb-5521-4a58-b433-1e6bfb5a0704.png">

### Minimal config to reproduce the issue

Just installed by default way
with default configuration

### Aditional information
MacOS 12.5
Fish v3.5.1
NVIM v0.7.2
packer.nvim

**plugin list**
 • LuaSnip
 • cmp-buffer
 • cmp-nvim-lsp
 • colorbuddy.nvim
 • git.nvim
 • gitsigns.nvim
 • go.nvim
 • guihua.lua
 • lspkind-nvim
 • lspsaga.nvim
 • lualine.nvim
 • markdown-preview.nvim
 • mason-lspconfig.nvim
 • mason.nvim
 • navigator.lua
 • neosolarized.nvim
 • null-ls.nvim
 • nvim-autopairs
 • nvim-bufferline.lua
 • nvim-cmp
 • nvim-colorizer.lua
 • nvim-dap
 • nvim-lspconfig
 • nvim-treesitter
 • nvim-ts-autotag
 • nvim-web-devicons
 • packer.nvim
 • plenary.nvim
 • prettier.nvim
 • rust-tools.nvim
 • telescope-file-browser.nvim
 • telescope.nvim
 • zen-mode.nvim

**Comment by shadmansaleh** [comment]
Did you set your colorscheme before calling lualine setup ?

> plugin list
• LuaSnip
• cmp-buffer
• cmp-nvim-lsp
• colorbuddy.nvim
• git.nvim
• gitsigns.nvim
• go.nvim
• guihua.lua
• lspkind-nvim
• lspsaga.nvim
• lualine.nvim
• markdown-preview.nvim
• mason-lspconfig.nvim
• mason.nvim
• navigator.lua
• neosolarized.nvim
• null-ls.nvim
• nvim-autopairs
• nvim-bufferline.lua
• nvim-cmp
• nvim-colorizer.lua
• nvim-dap
• nvim-lspconfig
• nvim-treesitter
• nvim-ts-autotag
• nvim-web-devicons
• packer.nvim
• plenary.nvim
• prettier.nvim
• rust-tools.nvim
• telescope-file-browser.nvim
• telescope.nvim
• zen-mode.nvim

That's not minimal no matter how you look at it.

Something in your plugins or config has cleared the highlight groups created by lualine most likely it's the colorscheme you're using . Sorry but I'm not gonna dig through you config & plugins to figure out what plugin or where in your config have you done that . That's why bug reports must have an isolated minimal config.

**Comment by FinallyFinancialFreedom** [comment]
yes i encounter the same problem, yes the colorscheme i used caused this problem, I fixed it by putting `require('theme')` right before `require('lualine')`.
