### ISSUE TITLE
Feat: Set refresh option dynamically.

### ISSUE THREAD

**Issue by singlexyz** [nvim-lualine/lualine.nvim#909]
After executing `setup`, the value of the `refresh` option is fixed.

I want to modify the value in `refresh` before executing other functions, and modify it back after execution.

**Comment by shadmansaleh** [comment]
What would be the use case for it that can't be satisfied by the pre-existing refresh mechanics? 

https://github.com/nvim-lualine/lualine.nvim#refreshing-lualine

**Comment by singlexyz** [comment]
> What would be the use case for it that can't be satisfied by the pre-existing refresh mechanics?
> 
> https://github.com/nvim-lualine/lualine.nvim#refreshing-lualine

https://user-images.githubusercontent.com/4456413/207645962-b0f49444-cf74-466d-bdbf-640a17c29ac5.mov

In the place of `lualina_a`, I made a simple animation to displays text. This needs to be refreshed very quickly.
But keeping such a fast refresh, I don't know if there will be performance problems.
So I want to set the value to 80 before animation and 1000 after animation.

**Comment by shadmansaleh** [comment]
> But keeping such a fast refresh, I don't know if there will be performance problems.
So I want to set the value to 80 before animation and 1000 after animation.

lualine refreshes under 1ms so setting refresh to a lower value then 1000 shouldn't have any noticeable performance difference. I had set the default to 1000 because vim/nvim refreshes it's default status line roughly that often.

Also, you can create your own timer that repeats every 80ms and call `lualine.refresh` in there when you're doing the animation.
That's pretty much what refresh option in lualine itself does https://github.com/nvim-lualine/lualine.nvim/blob/bfa0d99ba6f98d077dd91779841f1c88b7b5c165/lua/lualine.lua#L493-L500

Otherwise, you could call the setup function to update value of option.
```lua
require'lualine'.setup {options = {refresh = {statusline = 80}}}
require'lualine'.setup {options = {refresh = {statusline = 1000}}}
```
