### ISSUE TITLE
Bug: Windows separator color

### ISSUE THREAD

**Issue by Yohnny777** [nvim-lualine/lualine.nvim#919]
![image](https://user-images.githubusercontent.com/67546750/209459054-b62c3108-99e1-446d-8fe0-03c5de1c4ca6.png)

Is this normal? I would like to change the color of this white block to black.

It seems to be window separator (when there's one window, the block isn't there).

I have my Window separator highlightcolor set:

```vim
hi WinSeparator guibg=#000000 guifg=#000000 gui=NONE
```

Any idea what it might be and how to change this?

**Comment by shadmansaleh** [comment]
This is normal. that's how neovim draws window borders. That character isn't part of status line of either window instead it marks the border.

**Comment by pinecat** [comment]
I recently ran into this problem. So, even though this issue is closed, I thought I'd post my solution here in case anyone else runs across this.  That area isn't actually part of the `WinSeparator` highlight group, as @shadmansaleh said.  It is actually part of `StatusLine`/`StatusLineNC` highlight group.  It seems that lualine does not have any sort of configuration for this area.  The following fixed it for me:
```lua
vim.api.nvim_set_hl(0, "StatusLine", { bg = "none" })
vim.api.nvim_set_hl(0, "StatusLineNC", { bg = "none" })
```
Or you can do `bg = "<whatever-color-you-want>"`.
