### ISSUE TITLE
how add count of todo-comments?

### ISSUE THREAD

**Issue by RAprogramm** [nvim-lualine/lualine.nvim#925]
i try to  find answers but there are absent.

**Comment by RAprogramm** [comment]
https://github.com/nvim-lualine/lualine.nvim/issues/199
i think is the same theme but there is no answer

**Comment by shadmansaleh** [comment]
Look into custom components. You can write a lua function to show number of TODO comments in lualine. 

You can use searchcount to search for TODO comments in the file. Or if you have treesitter comment installed you can count the number of todo comments in the TS tree.

Issue tracker is for bug reports not for questions like this. Also you ignored the issue template. And lualine won't be providing a built-in component for this. We can't provide built-in components for everything that's why custom components are there.
